kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
  namespace: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-pv  
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/jenkins"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-pvc
  labels:
    app: jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: jenkins-pv 
  resources:
    requests:
      storage: 5Gi
  volumeName: jenkins-pv
